import 'package:bitsdojo_window/bitsdojo_window.dart';
import 'package:ezo/core/layout/unified_scroll_behavior.dart';
import 'package:ezo/core/providers/locale_provider.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_quill/flutter_quill.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'core/router/app_router.dart';
import 'core/di/service_locator.dart';

// Generated by `flutter gen-l10n` into lib/l10n/
import 'l10n/app_localizations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Use path URL strategy on web so reset/verify links work without # prefix
  if (kIsWeb) usePathUrlStrategy();
  await ServiceLocator.instance.initialize();

  runApp(const ProviderScope(child: EzoPosApp()));

  doWhenWindowReady(() {
    const initialSize = Size(1280, 720);
    appWindow.minSize = const Size(800, 600);
    appWindow.size = initialSize;
    appWindow.alignment = Alignment.center;
    appWindow.title = 'AeroPOS';
    appWindow.show();
  });
}

class EzoPosApp extends ConsumerWidget {
  const EzoPosApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final appRouter = ref.watch(appRouterProvider);

    // Watch the locale provider — writing to it triggers a hot locale switch.
    final locale = ref.watch(localeProvider);

    return MaterialApp.router(
      routerConfig: appRouter,
      debugShowCheckedModeBanner: false,
      title: 'AeroPOS',
      scrollBehavior: UnifiedScrollBehavior(),

      // ── Locale ──────────────────────────────────────────────────────────────
      locale: locale,
      localizationsDelegates: [
        // Generated delegate for your app strings:
        AppLocalizations.delegate,
        // Flutter framework delegates:
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        // Flutter Quill:
        FlutterQuillLocalizations.delegate,
      ],
      supportedLocales: const [
        // Middle East
        Locale('en'), // English (default / fallback)
        Locale('ar'), // Arabic  (RTL)
        Locale('fa'), // Persian / Farsi (RTL)
        Locale('tr'), // Turkish
        // Europe
        Locale('de'), // German
        Locale('fr'), // French
        Locale('es'), // Spanish
        Locale('it'), // Italian
        Locale('nl'), // Dutch
      ],

      // ── Theme ───────────────────────────────────────────────────────────────
      theme: ThemeData(
        fontFamily: 'AppFont',
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true,
      ),
    );
  }
}
